  
name: Check

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'

jobs:
  check:
    runs-on: ubuntu-latest

    container:
      image: empereur7/babygrowth-rails-ci:latest
    env:
      RAILS_ENV: test
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: test
      DB_USERNAME: mysql
      DB_PASSWORD: mysql

    services:
      mysql:
        image: mysql:8.0.19
        ports:
          - 3306:3306
        options:  >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: mysql
          MYSQL_DATABASE: test

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle exec rake db:setup
      - run: bundle exec rake webpacker:install
      - run: bundle exec rake test