  
name: Check

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'

jobs:
  check:
    runs-on: ubuntu-latest

    container:
      image: empereur7/babygrowth-rails-ci:latest

    steps:
      - uses: actions/checkout@v2
      - run: bundle config path vendor/bundle
      - run: bundle install --jobs 4 --retry 3
      - uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql root password: 'mysql'
          mysql user: 'mysql'
          mysql password: 'mysql'
      - run: bundle exec rake db:setup
      - run: bundle exec rake webpacker:install
      - run: bundle exec rake test