  
name: Check

on:
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '**.md'

jobs:
  check:
    runs-on: ubuntu-latest

    container:
      image: empereur7/babygrowth-rails-ci:latest

    steps:
      - uses: actions/checkout@v2
      - name: Cache gems
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: Cache node packages
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - run: bundle config path vendor/bundle
      - run: bundle install --jobs 4 --retry 3
      - uses: mirromutth/mysql-action@v1.1
        with:
          character set server: 'utf8'
          collation server: 'utf8_general_ci'
          mysql version: '8.0'
          mysql root password: 'mysql'
          mysql user: 'mysql'
          mysql password: 'mysql'
      - run: yarn install
      - run: sudo /etc/init.d/mysql start
      - run: bundle exec rake db:setup
      - run: bundle exec rake webpacker:install
      - run: bundle exec rake test